### ISSUE TITLE
How to get the superscript of an iter operator

### ISSUE THREAD

**Issue by canary00** [fadoss/maude-bindings#2]
Hi.

I have a question.

I cannot get a superscript from a term. In following case, it's 3.
```
import maude

def reconstruct(term: maude.Term) -> str:
    sym = term.symbol()
    args = [reconstruct(arg)
            for arg in term.arguments()]
    if args:
        return f'{sym}({",".join(args)})'
    return str(sym)

if __name__ == '__main__':
    maude.init()
    maude.input('fmod ABC is pr INT . ops a b : -> Int . endfm')
    m = maude.getModule('ABC')
    t = m.parseTerm('3')
    str_t = reconstruct(t)
    t2 = m.parseTerm(str_t)
    t3 = m.parseTerm('s_^3(0)')
    assert t == t3
    # assert t == t2  # expected to hold

    t4 = m.parseTerm('s s s (a + b)')
    str_t4 = reconstruct(t4)
    t5 = m.parseTerm(str_t4)
    assert t4 == t5   # expected to hold
```

**Comment by ningit** [comment]
The library does not currently have explicit support for obtaining the exponent of [iterable operators](https://maude.lcc.uma.es/maude321-manual-html/maude-manualch4.html#x19-470004.4.2). However, the only reason is that no one has considered this case before. It will be easy to have a method doing so in the [`Term`](https://fadoss.github.io/maude-bindings/#maude.Term) class for the next version of the library. For the moment, the following function can be used
```python
def get_iter_superscript(term: maude.Term) -> int:
    term_str = term.prettyPrint(0)
    try:
        first_paren = term_str.index('(')
        caret = term_str[:first_paren].index('^')
        return int(term_str[caret+1:first_paren])
    except ValueError:
        return 1
```
It parses the exponent from the desugared textual representation of the term (the output for operators without the `iter` attribute is 1).

Your `reconstruct` function can then be fixed as follows:
```python
def reconstruct(term: maude.Term) -> str:
    sym = term.symbol()
    args = [reconstruct(arg) for arg in term.arguments()]
    if str(sym) in ('<Qids>', '<Floats>', '<Strings>'):
    	return str(term)  # special constants
    if args:
        exponent = get_iter_superscript(term)
        exponent = f'^{exponent}' if exponent > 1 else ''
        return f'{sym}{exponent}({",".join(args)})'
    return str(sym)
```
where we call the previous `get_iter_superscript` function and add the exponent if required. The conditional before `if args` handles the other special case that the `reconstruct` function may encounter: builtin constants like quoted identifiers, floating-point numbers, and strings, which cannot be characterized by their symbols and arguments, as you can see in the [Maude prelude](https://github.com/SRI-CSL/Maude/blob/3.2.1/src/Main/prelude.maude#L537).

By the way, if you want to reconstruct the term as a `Term` object instead of a string, it is more efficient to build it using the [`Symbol.makeTerm`](https://fadoss.github.io/maude-bindings/#maude.Symbol.makeTerm) method. However, building `iter` operators is not directly supported by the library yet, so this add a bit of complication.
```python
def reconstruct_as_term(term: maude.Term) -> maude.Term:
    sym = term.symbol()
    if term.isVariable() or str(sym) in ('<Qids>', '<Floats>', '<Strings>'):
    	return term  # special constants
    args = [reconstruct_as_term(arg) for arg in term.arguments()]
    # iter operators
    if (exponent := get_iter_superscript(term)) > 1:
        m = sym.getModule()
        var = f'X:{args[0].getSort()}'
        # we parse a term s_^exponent(X) and instantiate it
        return maude.Substitution({m.parseTerm(var): args[0]}).instantiate(
        	 m.parseTerm(f'{sym}^{exponent}({var})'))
    return sym.makeTerm(args)
```

**Comment by canary00** [comment]
Thank you very much.
It worked well.
Your thoughtful advice helped me a lot.
